language:
  - java
  - node_js

android:
  components:
    - build-tools-25.0.3
    - android-25
    - sys-img-armeabi-v7a-android-25

node_js:
  - "6.9.0"
os:
  - linux

sudo: true

branches:
  only:
  - master


scripts:
  - ./bin/install-tns.sh
  - ./bin/install-android.sh

